# python3
# Copyright 2021 InstaDeep Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""MADDPG system implementation."""

import copy
import dataclasses
from typing import Dict, Iterator, List, Optional, Union

import reverb
import sonnet as snt
import tensorflow as tf
from acme import datasets, specs, types

# TODO: Change the adders to mava once it is working
from acme.adders import reverb as adders
from acme.tf import networks
from acme.tf import utils as tf2_utils
from acme.utils import counting, loggers

from mava import core
from mava.systems import system
from mava.systems.tf import executors
from mava.systems.tf.builders import SystemBuilder
from mava.systems.tf.maddpg import training

NestedLogger = Union[loggers.Logger, Dict[str, loggers.Logger]]


@dataclasses.dataclass
class MADDPGConfig:
    """Configuration options for the MADDPG system.
    Args:
            environment_spec: description of the actions, observations, etc.
            policy_network: the online (optimized) policy.
            critic_network: the online critic.
            observation_network: optional network to transform the observations before
              they are fed into any network.
            discount: discount to use for TD updates.
            batch_size: batch size for updates.
            prefetch_size: size to prefetch from replay.
            target_update_period: number of learner steps to perform before updating
              the target networks.
            min_replay_size: minimum replay size before updating.
            max_replay_size: maximum replay size.
            samples_per_insert: number of samples to take from replay for every insert
              that is made.
            n_step: number of steps to squash into a single transition.
            sigma: standard deviation of zero-mean, Gaussian exploration noise.
            clipping: whether to clip gradients by global norm.
            logger: logger object to be used by learner.
            counter: counter object used to keep track of steps.
            checkpoint: boolean indicating whether to checkpoint the learner.
            replay_table_name: string indicating what name to give the replay table."""

    agents: List[str]
    agent_types: List[str]
    environment_spec: specs.EnvironmentSpec
    policy_networks: Dict[str, snt.Module]
    critic_networks: Dict[str, snt.Module]
    observation_networks: Dict[str, snt.Module]
    shared_weights: bool = False
    discount: float = 0.99
    batch_size: int = 256
    prefetch_size: int = 4
    target_update_period: int = 100
    min_replay_size: int = 1000
    max_replay_size: int = 1000000
    samples_per_insert: float = 32.0
    n_step: int = 5
    sigma: float = 0.3
    clipping: bool = True
    logger: loggers.Logger = None
    counter: counting.Counter = None
    checkpoint: bool = True
    replay_table_name: str = adders.DEFAULT_PRIORITY_TABLE


class MADDPGBuilder(SystemBuilder):
    """Builder for D4PG which constructs individual components of the agent."""

    """Defines an interface for defining the components of an RL system.
      Implementations of this interface contain a complete specification of a
      concrete RL system. An instance of this class can be used to build an
      RL system which interacts with the environment either locally or in a
      distributed setup.
      """

    def __init__(self, config: MADDPGConfig):
        self._config = config

    def make_replay_tables(
        self,
        environment_spec: specs.EnvironmentSpec,
    ):
        """Create tables to insert data into."""

    def make_dataset_iterator(
        self,
        replay_client: reverb.Client,
    ):
        """Create a dataset iterator to use for learning/updating the agent."""

    def make_adder(
        self,
        replay_client: reverb.Client,
    ):
        """Create an adder which records data generated by the executor/environment.
        Args:
          replay_client: Reverb Client which points to the replay server.
        """

    def make_executor(
        self,
        policy_networks,
        adder: Optional[adders.Adder] = None,
        variable_source: Optional[core.VariableSource] = None,
    ):
        """Create an executer instance.
        Args:
          policy_networks: A struct of instance of all the different policy networks;
           this should be a callable
            which takes as input observations and returns actions.
          adder: How data is recorded (e.g. added to replay).
          variable_source: A source providing the necessary actor parameters.
        """

    def make_trainer(
        self,
        networks,
        dataset: Iterator[reverb.ReplaySample],
        replay_client: Optional[reverb.Client] = None,
        counter: Optional[counting.Counter] = None,
        logger: Optional[NestedLogger] = None,
        # TODO: eliminate checkpoint and move it outside.
        checkpoint: bool = False,
    ):
        """Creates an instance of the trainer.
        Args:
          networks: struct describing the networks needed by the trainer; this can
            be specific to the trainer in question.
          dataset: iterator over samples from replay.
          replay_client: client which allows communication with replay, e.g. in
            order to update priorities.
          counter: a Counter which allows for recording of counts (learner steps,
            actor steps, etc.) distributed throughout the agent.
          logger: Logger object for logging metadata.
          checkpoint: bool controlling whether the learner checkpoints itself.
        """


class MADDPG(system.System):
    """MADDPG system.
    This implements a single-process DDPG system. This is an actor-critic based
    system that generates data via a behavior policy, inserts N-step transitions into
    a replay buffer, and periodically updates the policies of each agent
    (and as a result the behavior) by sampling uniformly from this buffer.
    """

    def __init__(
        self,
        agents: List[str],
        agent_types: List[str],
        environment_spec: specs.EnvironmentSpec,
        policy_networks: Dict[str, snt.Module],
        critic_networks: Dict[str, snt.Module],
        observation_networks: Dict[str, snt.Module],
        shared_weights: bool = False,
        discount: float = 0.99,
        batch_size: int = 256,
        prefetch_size: int = 4,
        target_update_period: int = 100,
        min_replay_size: int = 1000,
        max_replay_size: int = 1000000,
        samples_per_insert: float = 32.0,
        n_step: int = 5,
        sigma: float = 0.3,
        clipping: bool = True,
        logger: loggers.Logger = None,
        counter: counting.Counter = None,
        checkpoint: bool = True,
        replay_table_name: str = adders.DEFAULT_PRIORITY_TABLE,
    ):
        """Initialize the system.
        Args:
          environment_spec: description of the actions, observations, etc.
          policy_network: the online (optimized) policy.
          critic_network: the online critic.
          observation_network: optional network to transform the observations before
            they are fed into any network.
          discount: discount to use for TD updates.
          batch_size: batch size for updates.
          prefetch_size: size to prefetch from replay.
          target_update_period: number of learner steps to perform before updating
            the target networks.
          min_replay_size: minimum replay size before updating.
          max_replay_size: maximum replay size.
          samples_per_insert: number of samples to take from replay for every insert
            that is made.
          n_step: number of steps to squash into a single transition.
          sigma: standard deviation of zero-mean, Gaussian exploration noise.
          clipping: whether to clip gradients by global norm.
          logger: logger object to be used by learner.
          counter: counter object used to keep track of steps.
          checkpoint: boolean indicating whether to checkpoint the learner.
          replay_table_name: string indicating what name to give the replay table.
        """
        # builder = MADDPGBuilder(
        #     MADDPGConfig(
        #         agents=agents,
        #         agent_types=agent_types,
        #         environment_spec=environment_spec,
        #         policy_networks=policy_networks,
        #         critic_networks=critic_networks,
        #         observation_networks=observation_networks,
        #         shared_weights=shared_weights,
        #         discount=discount,
        #         batch_size=batch_size,
        #         prefetch_size=prefetch_size,
        #         target_update_period=target_update_period,
        #         min_replay_size=min_replay_size,
        #         max_replay_size=max_replay_size,
        #         samples_per_insert=samples_per_insert,
        #         n_step=n_step,
        #         sigma=sigma,
        #         clipping=clipping,
        #         logger=logger,
        #         counter=counter,
        #         checkpoint=checkpoint,
        #         replay_table_name=replay_table_name,
        #     )
        # )

        behavior_networks = {}
        target_policy_networks = {}
        target_critic_networks = {}
        target_observation_networks = {}

        create_observation_networks = False
        if observation_networks is None:
            observation_networks = {}
            create_observation_networks = True

        # Create a replay server to add data to. This uses no limiter behavior in
        # order to allow the Agent interface to handle it.
        replay_table = reverb.Table(
            name="replay_table_name",
            sampler=reverb.selectors.Uniform(),
            remover=reverb.selectors.Fifo(),
            max_size=max_replay_size,
            rate_limiter=reverb.rate_limiters.MinSize(1),
            signature=adders.NStepTransitionAdder.signature(environment_spec),
        )
        self._server = reverb.Server([replay_table], port=None)

        # The adder is used to insert observations into replay.
        address = f"localhost:{self._server.port}"
        adder = adders.NStepTransitionAdder(
            priority_fns={replay_table_name: lambda x: 1.0},
            client=reverb.Client(address),
            n_step=n_step,
            discount=discount,
        )

        # The dataset provides an interface to sample from replay.
        dataset = datasets.make_reverb_dataset(
            table=replay_table_name,
            server_address=address,
            batch_size=batch_size,
            prefetch_size=prefetch_size,
        )

        agent_keys = self._agent_type if shared_weights else self._agents

        for agent_key in agent_keys:

            # Make sure observation network is a Sonnet Module.
            if create_observation_networks:
                observation_network: types.TensorTransformation = tf.identity
                observation_network = tf2_utils.to_sonnet_module(observation_network)
                observation_networks[agent_key] = observation_network

            # Get observation and action specs.
            act_spec = environment_spec[agent_key].actions
            obs_spec = environment_spec[agent_key].observations
            emb_spec = tf2_utils.create_variables(
                observation_networks[agent_key], [obs_spec]
            )

            # Create target networks.
            target_policy_network = copy.deepcopy(policy_networks[agent_key])
            target_critic_network = copy.deepcopy(critic_networks[agent_key])
            target_observation_network = copy.deepcopy(observation_networks[agent_key])

            target_policy_networks[agent_key] = target_policy_network
            target_critic_networks[agent_key] = target_critic_network
            target_observation_networks[agent_key] = target_observation_network

            # Create the behavior policy.
            behavior_network = snt.Sequential(
                [
                    observation_network,
                    policy_networks[agent_key],
                    networks.ClippedGaussian(sigma),
                    networks.ClipToSpec(act_spec),
                ]
            )
            behavior_networks[agent_key] = behavior_network

            # Create variables.
            tf2_utils.create_variables(policy_networks[agent_key], [emb_spec])
            tf2_utils.create_variables(critic_networks[agent_key], [emb_spec, act_spec])
            tf2_utils.create_variables(target_policy_network, [emb_spec])
            tf2_utils.create_variables(target_critic_network, [emb_spec, act_spec])
            tf2_utils.create_variables(target_observation_network, [obs_spec])

        # Create the actor which defines how we take actions.
        executor = executors.FeedForwardExecutor(
            policy_networks=behavior_networks,
            shared_weights=shared_weights,
            adder=adder,
        )

        # Create optimizers.
        policy_optimizer = snt.optimizers.Adam(learning_rate=1e-4)
        critic_optimizer = snt.optimizers.Adam(learning_rate=1e-4)

        # The learner updates the parameters (and initializes them).
        trainer = training.MADDPGTrainer(
            agents=agents,
            agent_types=agent_types,
            policy_networks=policy_networks,
            critic_networks=critic_networks,
            observation_networks=observation_networks,
            target_policy_networks=target_policy_networks,
            target_critic_networks=target_critic_networks,
            target_observation_networks=target_observation_networks,
            shared_weights=shared_weights,
            policy_optimizer=policy_optimizer,
            critic_optimizer=critic_optimizer,
            clipping=clipping,
            discount=discount,
            target_update_period=target_update_period,
            dataset=dataset,
            counter=counter,
            logger=logger,
            checkpoint=checkpoint,
        )

        super().__init__(
            executor=executor,
            trainer=trainer,
            min_observations=max(batch_size, min_replay_size),
            observations_per_step=float(batch_size) / samples_per_insert,
        )
