# ---Recurrent Structure Networks---
actor_network:
  use_layer_norm: True
  activation: "tanh"
  pre_torso_layer_sizes: [128]
  post_torso_layer_sizes: [128]

critic_network:
  use_layer_norm: False
  activation: "tanh"
  pre_torso_layer_sizes: [128]
  post_torso_layer_sizes: [128]
