system.actor_lr: choice(2.5e-4, 5e-4, 1e-3)
system.critic_lr: choice(2.5e-4, 5e-4, 1e-3)
system.rollout_length: choice(128, 256)
system.ppo_epochs: choice(2,4,8)
system.num_minibatches: choice(2,4,8)
system.max_grad_norm: choice(0.5,5.0,10.0)
system.clip_eps: choice(0.05, 0.1, 0.2)
system.ent_coef: choice(2e-6, 0.01, 0.02, 0.05)
