# --- Logging options ---

use_tf: False # Whether to use tensorboard logging.
base_exp_path: results # Base path for logging.
use_json: False # Whether to log marl-eval style to json files.

# --- Neptune logging ---
use_neptune: False

# --- Other logger kwargs ---
kwargs:
  neptune_project: Instadeep/Mava
  neptune_tag: [rware] # The system name will be added automatically if 'use_neptune is True' .
  json_path: ~ # If set, json files will be logged to a set path so that multiple experiments can
    # write to the same json file for easy downstream aggregation and plotting with marl-eval.

# --- Checkpointing ---
checkpointing:
  save_model: False # Whether to save model checkpoints.
  save_args:
    save_interval_steps: 1 # Number of steps between saving checkpoints.
    max_to_keep: 1 # Maximum number of checkpoints to keep.
    keep_period: ~ # Don't delete any checkpoint where step % keep_period == 0
    checkpoint_uid: ~ # Unique identifier for checkpoint to save. Defaults to timestamp

  load_model: False # Whether to load model checkpoints.
  load_args:
    checkpoint_uid: "" # Unique identifier for checkpoint to load.
