defaults:
  - logger: logger
  - arch: anakin
  - system: ppo/ff_cent_ppo
  - network: mlp  # [mlp, cnn]
  - env: rware  # [cleaner, connector, gigastep, lbf, mabrax, matrax, rware, smax]
  - _self_

hydra:
  searchpath:
    - file://mava/configs