defaults:
  - logger: logger
  - arch: sebulba
  - system: ppo/ff_ippo
  - network: mlp  # [mlp, continuous_mlp, cnn]
  - env: rware_gym  # [rware_gym, lbf_gym]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
