defaults:
  - _self_
  - logger: logger
  - arch: anakin
  - system: q_learning/rec_iql
  - network: rnn # [rnn, rcnn]
  - env: rware # [cleaner, connector, vector-connector, lbf, rware]

hydra:
  searchpath:
    - file://mava/configs
