defaults:
  - logger: logger
  - arch: anakin
  - system: ppo/rec_ippo
  - network: rnn  # [rnn, rcnn]
  - env: rware  # [cleaner, connector, gigastep, lbf, mabrax, matrax, rware, smax, mpe]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
