#after any changes to the Gemfile, execute bundle update!
source "https://rubygems.org"
gemspec
gem "github-pages","~> 214", group: :jekyll_plugins
# Delete the following lines if not on Windows:
# Performance-booster for watching directories on Windows
gem "wdm", ">= 0.1.0" if Gem.win_platform?
gem "webrick", "~> 1.7"

# Update for https://github.com/advisories/GHSA-52p9-v744-mwjj
gem "kramdown", ">= 2.3.1"

# Update for security issue
gem "rexml", ">= 3.2.5"
