# --- Defaults ---

# --- Experiment params ---
defaults:
  - _self_
  - env: MultiCVRP # [RobotWarehouse, MultiCVRP]

BATCH_SIZE: 4  # Parallel updates / environments
TOTAL_TIMESTEPS: 204800  # Number of training timesteps
SEED: 42

# --- RL hyperparameters ---
LR: 5e-3
ACTIVATION: relu
UPDATE_EPOCHS: 1
NUM_MINIBATCHES: 1
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ROLLOUT_LENGTH: 128  # Length of each rollout

# --- Logging options ---
USE_TF: true
USE_SACRED: true
