# --- Environment Configs---
defaults:
  - _self_
  - scenario: simple_spread_3ag # [simple_spread_3ag, simple_spread_5ag, simple_spread_10ag]

env_name: MPE  # Used for logging purposes and selection of the corresponding wrapper.

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return

implicit_agent_id: False
# Whether or not to log the winrate of this environment. This should not be changed as not all
# environments have a winrate metric.
log_win_rate: False

kwargs:
  action_type: Continuous # Whether agent action spaces are Continuous or "Discrete".
