# ---Environment Configs---
defaults:
  - _self_
  - scenario: multicvrp-2v-20c # [multicvrp-2v-20c, multicvrp-2v-6c]

env_name: MultiCVRP

# Whether the environment observations encode implicit agent IDs. If True, the AgentID wrapper is not used.
# This should not be changed.
implicit_agent_id: False

eval_metric: episode_return

log_win_rate: False

kwargs: {}
