name: CI 🧪

on: [ pull_request ]

jobs:
  linters:
    name: "Python ${{ matrix.python-version }} on ubuntu-latest"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: ["3.12", "3.11"]

    steps:
      - name: Checkout mava
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"
          enable-cache: true
          cache-dependency-glob: "uv.lock"  # invalidate cache when requirements file changes
          python-version: "${{ matrix.python-version }}"

      - uses: actions/setup-python@v5
        with:
            python-version: "${{ matrix.python-version }}"

      - name: Install python dependencies 🔧
        run: uv pip install . --group dev
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Run linters 🖌️
        run: pre-commit run --all-files --verbose
