name: integration-tests

on:
  pull_request:
    branches: [main]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 65
    strategy:
      fail-fast: false
      matrix:
        docker-image: ["python:3.8", "python:3.9", "python:3.10"]
    steps:
      - name: Checkout mava
        uses: actions/checkout@v2
      - name: Run integration tests in docker
        run: |
          docker run --mount "type=bind,src=$(pwd),dst=/tmp/mava" \
              -w "/tmp/mava" --rm ${{ matrix.docker-image }} /bin/bash bash_scripts/tests.sh true
