# --- Logging options ---
# Loggers can be enabled or disabled through the `enable` option. `_target_` specifies the class that is instantiated.
# All other options are specific to the logger.
# Custom loggers can be added by creating a new item in the `loggers` dictionary containing `_target_` and `enabled` keys.

base_exp_path: results/

loggers:
  console:
    _target_: mava.utils.logger.ConsoleLogger
    enabled: True
  tensorboard:
    _target_: mava.utils.logger.TensorboardLogger
    enabled: False

# --- Checkpointing ---
checkpointing:
  save_model: False # Whether to save model checkpoints.
  save_args:
    save_interval_steps: 1 # Number of steps between saving checkpoints.
    max_to_keep: 1 # Maximum number of checkpoints to keep.
    keep_period: ~ # Don't delete any checkpoint where step % keep_period == 0
    checkpoint_uid: ~ # Unique identifier for checkpoint to save. Defaults to timestamp
    path: ~
  load_model: False # Whether to load model checkpoints.
  load_args:
    checkpoint_uid: "" # Unique identifier for checkpoint to load.
